### ISSUE TITLE
Error using Python3 - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 594: invalid continuation byte

### ISSUE THREAD

**Issue by royopa** [hustlzp/Flask-Boost#16]
I have the error below with Python3.4

rodrigo@rodrigo-xubuntu:~/projects$ boost new your_project_name
Start generating project files.
Traceback (most recent call last):
  File "/usr/local/bin/boost", line 9, in <module>
    load_entry_point('Flask-Boost==0.4.4', 'console_scripts', 'boost')()
  File "/usr/local/lib/python3.4/dist-packages/flask_boost/cli.py", line 80, in main
    execute(args)
  File "/usr/local/lib/python3.4/dist-packages/flask_boost/cli.py", line 69, in execute
    _rewrite_and_copy(src_file, dst_file, project_name)
  File "/usr/local/lib/python3.4/dist-packages/flask_boost/cli.py", line 102, in _rewrite_and_copy
    for line in old_file:
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 594: invalid continuation byte

**Comment by hustlzp** [comment]
Thank you for reporting this. I will test it in Python3.

**Comment by hustlzp** [comment]
I have bumped version to 0.4.6 which fixes some Python3 issues:

* Fix project generation logic to support Python3.
* Use PyMySQL instead of MySQL-python to support Python3.

Unfortunately some packages are still not compatible with Python3 such as Fabric (Flask-Boost uses Fabric for deployment).

You can upgrade to the lateste version and try with Python3 :laughing:

**Comment by royopa** [comment]
Thanks, I will test!
